version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Africa/Lagos
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
