name: wirespot_backend
description: Lightweight 100% Free Dart Frog Backend for WireSpot Cloud & Mobile-Web Pairing.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0

dev_dependencies:
  test: ^1.24.0
